name: MOBI Lab
description: Modelling of Biodiversity laboratory at Czech University of Life Sciences
url: "https://petrkeil.github.io/website/"
baseurl:  "/website"
production_url: http://petrkeil.github.io.com/website
BASE_PATH : http://petrkeil.com/website

title: MOBI Lab

markdown: kramdown
permalink: /:categories/:title/

future: true
sass:
  sass_dir: css

plugins: ['jekyll-twitter-plugin']

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"




theme: jekyll-theme-cayman