# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Petr Keil
email: keil@fzp.czu.cz
description: > # this means to ignore newlines until "baseurl:"
  Macroecology, biogeography, statistics, all things related to scale.
baseurl: "/website/" # the subpath of your site, e.g. /blog
url: "https://petrkeil.github.io/website/" # the base hostname & protocol for your site
twitter_username: R_you_cereal
github_username:  petrkeil

# Build settings
markdown: kramdown
